---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age10rpv52su6hc58dl246053rdhkxq7ukfmzhjhptwvp80lmdgpuc2q0c0m4t
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age10rpv52su6hc58dl246053rdhkxq7ukfmzhjhptwvp80lmdgpuc2q0c0m4t
