---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1euypjjkgtafetreqs34c2yj77ljcunqjyw4rjce9jescejdgddzsm0q4j7
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1euypjjkgtafetreqs34c2yj77ljcunqjyw4rjce9jescejdgddzsm0q4j7
