# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:5OYL6O6I+TxRC7g6McEWy5++Hi8I8kA=,iv:oFPd09EGa0F63E8EB+dvZFeZrDzuD0pupZHtdV8z7I0=,tag:kzBRtMRIc/kmbl/DLk9e6w==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:3I36VKuA8wIyQW5FRcBAcKmjZw9o2rdPG6cfr4o/6pOOWWmXGw==,iv:J/7HEKICOWjrDRpMMcrb26NvFRSO+szn9xCtD3LKzPY=,tag:LB+NalNwPFP+ku3N16p3nQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:DUzb3+m/YuvBPrLILc8vA/vFwbL94r2i,iv:2HA02JLiO3xaHmbEpe0asgIld/32KtqpWvR41+bFw0s=,tag:QNjSD4s0c+P8hIuVDCmP6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10rpv52su6hc58dl246053rdhkxq7ukfmzhjhptwvp80lmdgpuc2q0c0m4t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RnV2QytOeDY2Wk9OZWZs
            QSsvdWtKOWdOUVd5S0NmWk1GT0Q1dzNjbGp3Ci9Ha3JIMURpZmEvMnkweEFIS1kv
            c3o5allCSlpoUlgrZ201eFFJMmJuSU0KLS0tIGZYK1FBbUY2V1JxQnBmcUtwb3RG
            VVZOcS9qSk9uSkdJSzJmK0tqV0JJMzAKKIGQ4x+kQYAc6bZhQDoalvrozr6Zmc/Z
            TUrmVLTpqnUsgjdB6jChQtJM+tnTmkEN0uPFvm9AEcCnQq8w3nLf2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-12T09:01:47Z"
    mac: ENC[AES256_GCM,data:4rhhblVlJ+TXE3jLcZ/ioNIXbg/zk8xgWHlrQs4fmGU4t37JlAnxgBRSMpnCwoPTQwk3Gzuv0d5WXtMRtzAe/r8ubGcEtNkZgSb7UrubgDgP0eJikJiginDNc6LXKOrhIwrjQKbpW931FZE8N7DIk2j5RcyQVtKP/RjJYuitI3I=,iv:YRl6DFK9PiKVhW0TIUbB+5mAIbwYkgdrjZUp1/qHHts=,tag:lrNwcY7ZeImMCq9v9eUjrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
