# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:SC7sW0ME1GjvoMD+Lfg+BNxlGWXQ+6E=,iv:wT0+Dn/SP2Fylt/7JiXiDJIGQLyLps5FvqVzdwLumEM=,tag:W7ax9n/WULgouqkMoGw5+w==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:FcTrT8vohcYjoeKG/KORN+5mDTUqSYoE/yV0BECoWLKasdYa5w==,iv:YhuRau47gDV2HgL9/oQk5E14S6/eSa9pBqFodUKeb1o=,tag:oFhfc6+YAeKcWylCaOhmLQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:eUl4+RAVdfeXE05c9GI9i6XCweqrf4/Q,iv:hT9aMOqygbn3Vxe8hAuNft0pV4QVVkrU08plh4W1074=,tag:Vy/heIK0IvxY8Ngc2dyAxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19t6yuaahx4auxcxv674gdxml4clt2ex0xhf4wfp4mszgdpv4yd5qvnsdvm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMTJMWkcxdnVHam93UFV1
            aC9hTytFMS9sL1d6T25mUExQUXhhQWJ4T0dRCkVabkdLamI5WU9UK2xpakVhQWlK
            UTB5QktzU2FDSHF4RVdDbmtkZUdTeUEKLS0tIHJyTm84enluWkJTamdNYUZzS1pO
            VXNnYUV1c21CWDBMTUY1RVJxR2toL3MKRye8JqKR+Ye/I/tLh8u7eOgghlfHnzAf
            O07TQ+uY5+zgPAYjsFNefsSMNz/A/imgWGxPJ8edKoXrziWDsiQfYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-16T23:24:52Z"
    mac: ENC[AES256_GCM,data:6OJiW0Yq6aXhza4zridNQghiAVsvOunMvPVd07snpc7XEM71Vhl2ImR+HwLemRhorv8CkTjW7mNh/xQNRhVVaBdXwtijF6e2ksU5XSd23MSH7vMmo7+rFHTffBUkwYOzU/l2RnDwk2zVMjXfKcOqXgUYJ0SPj06HMwioCei/vuk=,iv:Y+zZmaVxKTBC42pJ7To6QnrtuKD6zg3idO1NXpBJqaM=,tag:UDDbLUE2PLb4oMDjf5/j8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
