# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:r16DMIehZRlrQiQuUiDTIskZ5PS2Jdg=,iv:SxnliJf9lnFA9TBo9bCXQgpWZNXsE1iEpnq4EWUom4k=,tag:D9XhtOKis6B4IuSRkZsToA==,type:str]
    api-key: ENC[AES256_GCM,data:uWOeL/8GQDrN3eTaZJjsNDvpATbuW7FUUUgblDG8qyd0KSvvnw==,iv:nwtRlzvR2Avod1UzQvzvK+iqSLiSq+XsOojPlAI7A6E=,tag:Z7ar0DwxfOey86HNgN0bOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1euypjjkgtafetreqs34c2yj77ljcunqjyw4rjce9jescejdgddzsm0q4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ekdCVlNBbHYxMnRDdjJh
            Vi8vRXZSd281ZzRzOXV5Tm0xUkg0QVMvcVhvCkdNRUxYMjVyNW5rS0huNHpnVHdj
            UWdLNmxjL3pJaHVzbWUrNWVOakNHZTgKLS0tIERaT1hTOU1pelhCUWZWdFhid2h5
            L2hkdEtUdEVYTW5waFM0b1k4MzVHdE0KrawWdJxM84OdN3GiPDtmoCjSwYS8f7yl
            VWcAF70atHeM2g4/Tquxh3vzNKbGIecgGOhlCUN6z0gwt0tBnVvDqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-17T00:21:40Z"
    mac: ENC[AES256_GCM,data:1w+Qqt9LxHoZdbgs1tvketCEA9T/ivR0kpSW6mDfak2Ybo3t1jys6Jysu2cLj4TBivJHKS54XTCjk0+X9V4uLyFc2mq4nQgnBvd8MmnsvTPsSYTdrsqxaR8iwcknkc2F0wGuhgaEuKcKVs7ifgL9Lwl7XSr+BJUE4sfOdF/MqLw=,iv:OM2YWXxvmdbBfGMgizXDvOETTldEysQCjFlvkE1pcbA=,tag:9hl2o2J4k29zG1L/3i6dlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
