# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:Ytz9vb8LIpUOnoGK43+RUmXuBWgEcRs=,iv:Oqq9p14zY2GGS7Jn6rtj5GsnC9GavE6Du8updIcTFOc=,tag:AI8X24WfXQE0su8jn5v73A==,type:str]
    api-key: ENC[AES256_GCM,data:YR660X7rL9GZGkYzWFOTig7b/z69V5/715SASll0xjWYyjZnWA==,iv:dSNw+PbbQRHqV6qxFOA/f9n6LaaxE+sFyP6OKYN2fLI=,tag:iOB9MWqwuKVaA9+XHbYOSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10rpv52su6hc58dl246053rdhkxq7ukfmzhjhptwvp80lmdgpuc2q0c0m4t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZmUwUkw2dkcrRkh5UTFN
            dnFmcVJuWTNDMlY5U1I5d2Q1VWE1NmRFZEhFCmJWL3NZUnpPNzJrWC8zU0JEanhI
            ZzE4VGNGWTh4VHBLRVo3b243b2FnaUkKLS0tIFRSbWIyRGdjWXBzZzlJM1U2Sm82
            K2hncU0zYncvaDFGTDhmejBIUFpoSGMKlMxyvXn/NftQh3hVginbhK2fyl1E+dcw
            4OcPQmYD7b4dXwhKMOFKi/qahU3oairEHKBatWj964OOBtAzrR39Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-12T09:01:47Z"
    mac: ENC[AES256_GCM,data:8FkeCaDMel+IVSJB3N+VSgtlTRnl42cDY/7w7YOIv3nXzbJlffXtaBzdRF1gEZVhewxShHWaovO+nw2oaxbFR3vFH2bArLoslToYoKIfcQd2hGKPtntQrASRkRSh7o8h5mR/59GuMY6RZagNTDlFgxfSLRnQUP/tJPg5L75f62M=,iv:qElS2ruv3hEVw3A/chyA9E5viJ0aV+vCsliQ4X6DzwE=,tag:Vy1WzgOKQBT+erBMRoeIIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
