---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE:
  METALLB_LB_RANGE: 192.168.86.150-192.168.86.250
  METALLB_K8S_GATEWAY_ADDR: 192.168.86.150
  METALLB_TRAEFIK_ADDR: 192.168.86.151
