---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE:
  METALLB_LB_RANGE: 192.168.86.152-192.168.86.252
  METALLB_K8S_GATEWAY_ADDR: 192.168.86.153
  METALLB_TRAEFIK_ADDR: 192.168.86.154
