# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:oaD/zG5WFfS/YkKSNw5R/r7dYQ==,iv:K+xUMGhkVOxuCCslOOHb/JqV4EgMncVm8vCSKrep7qI=,tag:TLpAPoJ+fz2Q3ufz0um0Ug==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:XOnd5MTF/fer66Lpl6LtOXEr19cKk9M=,iv:QV/OmM0qhpJ1dDdYT13lg5rw8IlIVDwKLjbC+YzwtzU=,tag:Cg2pSNCpoLuFDFy3qBTPqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19t6yuaahx4auxcxv674gdxml4clt2ex0xhf4wfp4mszgdpv4yd5qvnsdvm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteUdMQVYxZTF4eHZialdD
            QnJTS3hTbGtHWkhwaTBsS2ZzNWY2WkthZUNBCllRRWQ0cVNtNCthT1ZXYVVnanhU
            NWxXODdYbk02RDJ5WGUzWVcwTG9PcUkKLS0tIGN2UzFxa0R6dUdtWHQ5U21VSjBE
            UThIQktSdFZELzBsSU5YbXJ0MWVzdEEK4WuFYj1vgxfIdU/MqqRLsOWTq8F6OPVD
            5grDP3e1VJucGXpgNu79qH0wsjkTadYw0+sUCvvMYkJlrj/0ZdxeSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-16T23:24:52Z"
    mac: ENC[AES256_GCM,data:A5CU/xP14IwEcGbTwv2ller78qSpTQZVRdg10o2ita+A4S8NGn4Hs6/Jx9SkOrm8gsL8LwnmWvza5LziqEOPDXn2dj84ppoYmUneN3nmtU8Tcx27wPpL5aRgFjedyBR/Sjmdhjx8k+Iq9acWfss9IKQ3eFtTXRQsTjp3dciq3HM=,iv:udt6Xdg7gtvnRYd9z7SeS/3y4FQyB3JlAcSWN7NNq44=,tag:QJX9RMcyR6lkvQGlPbb3OA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
