# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Xjh65bQyoRj9gwZ7PsjlVphG3w==,iv:rS1bTYzn0ci4XIFWNQekWK09NIQ1dAid1jkoS3JM6nw=,tag:kExUW4MwCS2/0IBitAnjNg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Kt3blmct+v7chDl3Pm7nrvXqTZHC2aI=,iv:5s8yGGnwrEA+3/ytNBCxGjUNDinxYUgJ+kLixia2sI0=,tag:6xK71YSKcQcFcRPKvjWBIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1euypjjkgtafetreqs34c2yj77ljcunqjyw4rjce9jescejdgddzsm0q4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOStNTVJESG8vVlBIWm80
            aUFaOWV1NGZ2NE1ZRjVDZGQ5ZmxvWmZlbVQwCitDYVNWdjR6RTVHTnR2QnBhM3Zh
            VnExSFB1ZTFKRkQ3Q1FIOGVOQmpBazgKLS0tIG5MWDEvc0IrdTYyaFlBajQ3bXN3
            TFhhR2gzcXFHT3A4YUxhZlJGcU5NazAKbM7EupwY6GKpJnkEr8Lw1hKcm2+IEoLP
            YibvWY6IjbQ8/+dSO9Jpiq9SZM4LEG95uxnq+lvzVxzJCy48incgWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-17T00:21:40Z"
    mac: ENC[AES256_GCM,data:TWxJ9rJDLoJ3UthmAYldTxvhCDGMb6PBGSI+4v4qRL0DFUXuk6fg7IKSAXAEBu/xE5sLAbFazO8N90x/v1e6cIwU7LLV9FqVC7ptu/QU2jwe6gOYpU6NQfV5LsT6vJmYYvCo91bLDfRwUtZneU8cjRhlFuXN8AN1gmoQxL628NU=,iv:nzQCXDmvR8orAvi5JZBA1c25DxVww5QDw9h0fX0Bcgc=,tag:ZFEQ/q75bz24ajvxqWDOMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
