kind: Secret
ansible_user: ENC[AES256_GCM,data:7/FXUmfJesDkHA==,iv:uVyNJ+fQ6ki99tivnp5odSiJMwp2JwRi6XuVM1qpNvM=,tag:6vLvWbZcJx3id214B5yohA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:i4KubrI1Apo=,iv:c64HJb1owFqYD1NABK/wbQrHgUHS7ON7jnwDHDg+Ugg=,tag:MlnDaoGjEWpdy6cJ8rY8JQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10rpv52su6hc58dl246053rdhkxq7ukfmzhjhptwvp80lmdgpuc2q0c0m4t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VzFnT0F3TmtVK0JyVDFv
            VFgzY2gzTlFtYzRZL1VYYklROTN5UnpEVnhJCk5XNUdaSFlIWkhLdWtlRkROa0ZN
            WXl0dS9Sam5pREJlTUxMcUJUNlpRV0EKLS0tIDJHa2pBUm44SUtYNEhPcGVpVUpl
            b0dNL1ZzZlhRTmpBelZUejlvR0tkZlEKTS4EkJnbDEHpEmJ+XuQcwDHdB7vCwBok
            Ysl5Fn4R/KX47smiEQp9bNuygmQm1FTbVimZmiD6srVoS/uMG1ej3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-12T09:01:47Z"
    mac: ENC[AES256_GCM,data:4QjoszrcXtshui+0Umf7supe4+8yzG+GcEK+mtMVl1Oa9OWh1cU5PXoufLVTEefBCvXKRnn96Yx2JPB3igPiPIgWHAtUvXsrQY2o+uRzli+0DjbrssnRSD/JAVaGkyq09FOpLZxQpebYfdPl8EjHfblTmdJAYUH7c/yDmMWmaVU=,iv:QzdPlTrqBF3VHUg4Hw6/kQLMmaQlluJxMYQOXuc+aVM=,tag:Zbtb9uk7ZgdhHTRNzhduGg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
