kind: Secret
ansible_user: ENC[AES256_GCM,data:ojVbZTrvK9EpMA==,iv:PJZNj5qH+bC4aPjtYsxnTNeSzGSUjPl/hYqZeXgypNc=,tag:skiB5r1SxukQUqUvOUty2g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:aN7/YB7YlKM=,iv:21ww3qk7PlCVY+KBNaR2k0x5izj0pBCpbvQhE2n7YW0=,tag:KoU5SfFROlgW7kTZGn0JPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1euypjjkgtafetreqs34c2yj77ljcunqjyw4rjce9jescejdgddzsm0q4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMmlYU09IeGNCR2xNVEY1
            aEpDUndCeHdSRXpnckpGQ2RCZ2NIOE1FQWhJCk1BUGZhdldYekhPckVuQ09RNFlP
            anZzYU45UmdvdWxGNEQ2ZFdhYnQ1OEUKLS0tIGtpU29EaEpwY0JsTnVIQmdGeUJ1
            UVZxTUswa00wS1poKyt4T3dkVi8rNUkKSl5TueNHBDArnFiuKZ5f8Kc8VjsgSIE3
            LysaziPPH33g0Oi3onnMjPa1uvFRUD6xIPF5WdnzZOnjHHiamT/dLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-17T00:21:40Z"
    mac: ENC[AES256_GCM,data:Bgk/Xphj4jHcSxk2xUoMwhvpmv2kqJdq36r5Nhah95E67kILFlxhQNnWWM5dgJN6MCO+ZV5DbAvuKKvFFq4dpZm35ZcHnsQAFclYMOg92RWHS3pnkvLDqYy8tfkbcXbt0fmvgKXomenL7M5BJhUejq3VRMdaFOPc+zmk9myXyBg=,iv:I5YX8dYVlhAyX2e/Y/T6ubPM9Yt4EtOmEvnOntLRycI=,tag:/BCVCKvBAWCHlmAvmIJHfg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
