# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ygs6hvdIBVZoIW+8j+PRRSn6+cqHVIU/f4TeO0LA37+6g7PngU6arw==,iv:qxBJS6wu/pOwgeXtShEVMR5skB5s21QbgZGc/mch2sc=,tag:pzXdz+bZJ3kvXT0x5D+8yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1euypjjkgtafetreqs34c2yj77ljcunqjyw4rjce9jescejdgddzsm0q4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydXJON0hQQjR5QTdPdkkz
            dkxMSkcvSXFybmtKdkRWK2VHQXJDRlZGTzNnCk1JZFAvOXB2TnBhbHp0MXBiV3RP
            Y0hOVnIvUDlEaUpCNEh2YmE0SUwxUGMKLS0tIDFQS2Q4amFMQzFZeHdmekpoTW5C
            c3R1RmRMdzFCZENoRlJ3WUNiZEtKbk0KIlh7kN3WpHH3t6Uhh2JhEyBkJSfLusEL
            yQqHuSK9HUPPWh1n1tSz4NzDaJgF4APpZvdy0vAQshVDFIz5WGGnKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-17T00:21:40Z"
    mac: ENC[AES256_GCM,data:Q95zegszdNlL/5RodZ+893XKkyeSGkPrq5ckIZ0JvwYKSpv7NcpjxHYWY350eLua/en+rRBCBvVgkUHaX8dr/Yx0aZSmJXmbRc/Zs6XErmZ80u3q6IkhWb1SHYO9TV1O4KG0zkDLLDynUMMCJbbHnYL2zxGiCH8i1myKUSbKPqw=,iv:CebHNBf1Aa9kGSS+D7irdXzUeMa2mUaBEkuSsfhyorQ=,tag:AG896PoAXDYFCNpLVvAWKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
